controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

create_category:
    path: /category/create
    controller: App\Controller\CategoryController::number
